# Generated by Django 3.1.7 on 2021-02-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tb_content',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.IntegerField()),
                ('Title', models.CharField(max_length=1000)),
                ('content', models.TextField()),
            ],
        ),
    ]
