# Generated by Django 3.1.7 on 2021-03-13 12:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_content',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tb_content',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tb_content',
            name='profile_img',
            field=models.ImageField(default='', upload_to='pics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tb_content',
            name='user_name',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
